<a href="https://colab.research.google.com/github/mcfatbeard57/Hands-On-ML-Tensor-FLow/blob/main/iris_FirstPreceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.datasets import load_iris


In [2]:
from sklearn.linear_model import Perceptron

Perceptron learning algo strongly resembles SGD

Scikit-Learn’s Perceptron class is equivalent to
using an SGDClassifier with the following hyperparameters: 

loss="perceptron",
learning_rate="constant", eta0=1 (the learning rate), and penalty=None (no regularization).

In [3]:
iris = load_iris()

In [4]:
X = iris.data[:,(2,3)]

In [5]:
y = (iris.target == 0).astype(np.int)

In [6]:
per_Clf = Perceptron(random_state= 42)

In [7]:
per_Clf.fit(X,y)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=42, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [9]:
per_Clf.intercept_

array([4.])

In [11]:
per_Clf.coef_

array([[-1.4, -2.2]])

In [13]:
y_pred = per_Clf.predict([[2,0.5]])

In [14]:
y_pred

array([1])