# Pytorch

Core use case -

- replace numpy to use GPU for fast computing
- automatic differention which can help in calculating gradients => you can implimenting ANNs

In [1]:
import torch

import numpy as np

# Tensors

A kind of data structure => multidimensional arrays or matrices
With tensors you enocode all your parameters.


In [2]:
data = [[9, 10],
        [4, 5], 
        [12, 13]]


tensor_data = torch.tensor(data)


print(tensor_data)

print(type(tensor_data))

tensor([[ 9, 10],
        [ 4,  5],
        [12, 13]])
<class 'torch.Tensor'>


In [3]:
tensor_data[0, 0]

tensor(9)

In [4]:
np_data = np.array([[9, 10],
        [4, 5], 
        [12, 13]])


tensor_data_np = torch.tensor(np_data)


print(tensor_data_np)

print(type(tensor_data_np))

tensor([[ 9, 10],
        [ 4,  5],
        [12, 13]])
<class 'torch.Tensor'>


In [5]:
ones_like_data = torch.ones_like(tensor_data_np)
ones_like_data

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [6]:
ones_like_data = torch.ones_like(np_data)
ones_like_data

TypeError: ignored

In [7]:
ones_like_data = torch.ones_like(data)
ones_like_data

TypeError: ignored

In [8]:
ones_like_data_random = torch.rand_like(tensor_data_np)
ones_like_data_random

RuntimeError: ignored

In [9]:
ones_like_data_random = torch.rand_like(tensor_data_np, dtype=torch.float)
ones_like_data_random

tensor([[0.1158, 0.5232],
        [0.7711, 0.1032],
        [0.8999, 0.9008]])

In [10]:
shape = (4,3,2)

rand_tensor = torch.rand(shape)
rand_tensor

tensor([[[0.8552, 0.3978],
         [0.3278, 0.8022],
         [0.9356, 0.7636]],

        [[0.9796, 0.9507],
         [0.1033, 0.4170],
         [0.1492, 0.2695]],

        [[0.9405, 0.1522],
         [0.4487, 0.9543],
         [0.4466, 0.7527]],

        [[0.1595, 0.8797],
         [0.2381, 0.9298],
         [0.0031, 0.6817]]])

In [11]:
rand_tensor.shape

torch.Size([4, 3, 2])

In [12]:
rand_tensor.dtype

torch.float32

In [13]:
rand_tensor.device

device(type='cpu')

In [14]:
ones = torch.ones(shape)
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [15]:
zeros = torch.zeros(shape)
zeros

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])

In [16]:
ones = torch.ones(shape)
ones*3

tensor([[[3., 3.],
         [3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.],
         [3., 3.]],

        [[3., 3.],
         [3., 3.],
         [3., 3.]]])

In [17]:
torch.cuda.is_available()

True

In [19]:
current_device = torch.cuda.current_device()

In [20]:
torch.cuda.get_device_name(current_device)

'Tesla K80'

In [21]:
!nvidia-smi

Sat Aug 28 07:58:26 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8    27W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [23]:
if torch.cuda.is_available():
  rand_tensor = rand_tensor.to("cuda") 
  print(rand_tensor.device)

cuda:0


# Concat operations -

In [27]:
ones = torch.ones(2,2)
ones

tensor([[1., 1.],
        [1., 1.]])

In [28]:
torch.cat([ones, ones, ones])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [29]:
torch.cat([ones, ones, ones], dim=1)


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

# Arithmatic Ops

In [31]:
y = ones @ ones.T
y

tensor([[2., 2.],
        [2., 2.]])

In [32]:
y = ones.matmul(ones.T)
y

tensor([[2., 2.],
        [2., 2.]])

In [33]:
y = ones * ones
y 

tensor([[1., 1.],
        [1., 1.]])

In [34]:
y = ones.mul(ones)
y 

tensor([[1., 1.],
        [1., 1.]])

In [36]:
fives = ones + 5
fives

tensor([[6., 6.],
        [6., 6.]])

In [37]:
fives.add_(5)

tensor([[11., 11.],
        [11., 11.]])

In [38]:
fives.item()

tensor([[11., 11.],
        [11., 11.]])

In [39]:
type(ones)

torch.Tensor

In [40]:
ones_np = ones.numpy()
type(ones_np)

numpy.ndarray

In [41]:
ones_tensor = torch.from_numpy(ones_np)
type(ones_tensor)

torch.Tensor